apiVersion: v1
kind: PersistentVolume
metadata:
  name: moviedb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host_mnt/c/moviedb/data"